# Generated by Django 5.2.7 on 2025-10-29 06:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('idProduct', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_key', models.IntegerField(unique=True)),
                ('product_description', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=200)),
                ('sanmar_mainframe_color', models.IntegerField()),
                ('size', models.CharField(max_length=200)),
                ('color_name', models.CharField(max_length=100)),
                ('piece_price', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Table Products',
                'verbose_name_plural': 'Tabel Products',
                'db_table': 'tmProducts',
            },
        ),
    ]
