# Generated by Django 5.2.7 on 2025-10-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
