# Generated by Django 5.2.7 on 2025-10-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youprint', '0002_products_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sanmar_mainframe_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
