# Generated by Django 5.2.7 on 2025-10-29 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youprint', '0003_alter_products_sanmar_mainframe_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='failed_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='skipped_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='success_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
