# Generated by Django 5.2.7 on 2025-10-29 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youprint', '0004_products_failed_rows_products_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Failed', 'Failed'), ('Success', 'Success')], default='Pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Upload Log',
                'verbose_name_plural': 'Upload Logs',
                'db_table': 'tmUploadLog',
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='failed_rows',
        ),
        migrations.RemoveField(
            model_name='products',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='skipped_rows',
        ),
        migrations.RemoveField(
            model_name='products',
            name='status',
        ),
        migrations.RemoveField(
            model_name='products',
            name='success_rows',
        ),
        migrations.RemoveField(
            model_name='products',
            name='total_rows',
        ),
        migrations.RemoveField(
            model_name='products',
            name='uploaded_at',
        ),
    ]
