# Generated by Django 5.2.7 on 2025-10-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youprint', '0005_uploadlog_remove_products_failed_rows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sanmar_mainframe_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='style',
            field=models.CharField(max_length=255),
        ),
    ]
