# Generated by Django 5.2.7 on 2025-10-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youprint', '0006_alter_products_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sanmar_mainframe_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='style',
            field=models.TextField(),
        ),
    ]
