# Generated by Django 5.2.7 on 2025-10-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youprint', '0007_alter_products_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='unique_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
